### ISSUE TITLE
QOI encoding

### ISSUE THREAD

**Issue by zertovitch** [jrcarter/Image_IO#1]
If you want to add an output format with compression, there is this pure Ada implementation of QOI :
https://github.com/Fabien-Chouteau/qoi-spark/

**Comment by jrcarter** [comment]
Cool. It should be fairly easy to use that.

Unfortunately, QOI is not widely supported, so it's not clear how much value being able to write it will be. I was looking at the PNG writing in [stb_image_write.h](https://github.com/nothings/stb/blob/af1a5bc352164740c1cc1354942b1c6b72eacb8a/stb_image_write.h), since PNG is quite widely supported, and was going to ask you if you had an Ada version of the Zlib compression it uses among your many compression algorithms, so I guess I'll ask that here.

**Comment by zertovitch** [comment]
There is an unstarted project named Zada for replacing Zlib-Ada's body with pure Ada code.
And some hints how to carry it out (including where to fish the Ada Deflate implementations for encoding and decoding data): https://sourceforge.net/projects/zada/

**Comment by jrcarter** [comment]
Is that this [Zlib-Ada](https://github.com/alire-project/zlib-ada)? It looks like it wouldn't be too big a job, especially for someone familiar with Zip-Ada's internals.

**Comment by zertovitch** [comment]
Yes, indeed.

**Comment by jrcarter** [comment]
Added Write_QOI
